[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"

[[constraint]]
  name = "cloud.google.com/go"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.31"

[[constraint]]
  name = "github.com/nsqio/go-nsq"
  version = "1.0.7"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"

[[constraint]]
  name = "github.com/hyperledger/fabric-sdk-go"
  revision = "9dad8aeef1cad811762f1c476eb6fdf459836471"
